#!/usr/bin/env perl

use warnings;
use strict;

use FindBin;
use JSON;

my @required_vars = qw/ server /;

# read in config json file
my $fh;
open($fh, '<', 'config.json')
   or open($fh, '<', "$ENV{HOME}/.betterbot.json")
   or open($fh, '<', "$ENV{HOME}/.config/betterbot.json")
   or open($fh, '<', "$ENV{HOME}/.config/betterbot/config.json")
   or die "ERROR: Could not open config file";

my $json = JSON->new;
my $config = $json->decode(do {local $/; <$fh>});
close($fh);

# ensure all required config variables are defined
foreach(@required_vars) {
   die "ERROR: Config missing required key: $_" unless $config->{$_};
}

# start the bot
unshift(@INC, "$FindBin::Bin/../lib");
require Bot::BetterBot;

Bot::BetterBot->new($config)->run();

